fix: Inline used parts of pkg:stagehand, remove dependency
GoogleCloudPlatform/functions-framework-dart pull request #261
Opened 2021-07-15 20:27 UTC by kevmoo

2021-07-16 18:23 UTC, grant approved these changes

2021-07-16 18:27 UTC, subfuzion requested changes
This looks great, @kevmoo. Can you give me a bit more time to review?

2021-07-16 21:37 UTC, kevmoo commented
> This looks great, @kevmoo. Can you give me a bit more time to review?

Sure, @subfuzion . It's just copy-paste + deleting things that weren't testing what we thought they were testing.

2021-07-19 22:48 UTC, subfuzion approved these changes
This is great, @kevmoo -- thanks for tackling this!

2021-07-19 22:49 UTC, merged